[package]
name = "grocery_bagger_9000"
version = "0.1.0"
authors = ["Alex Saveau <saveau.alexandre@gmail.com>"]
edition = "2021"
description = "TODO"
repository = "https://github.com/SUPERCILEX/grocery_bagger_9000"
keywords = ["bevy", "tetris", "puzzle"]
categories = ["games"]

[dependencies]
bevy = { version = "0.7.0", default-features = false, features = ["render", "bevy_winit", "x11"] }
bevy_prototype_lyon = "0.5.0"
bevy_screen_diags = { git = "https://github.com/SUPERCILEX/bevy_screen_diags" }
paste = "1.0.7"
static_init = "1.0.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"

[profile.web-release]
inherits = "release"
opt-level = "s"
strip = "debuginfo"
